name: Feature Push

on:
  push:
    branches:
      - 'feature/**'

permissions: {}

jobs:
  secret-scan:
    name: Secret Scan
    uses: ./.github/workflows/_secret-scan.yml
    with:
      changed_only: true
      base_sha: ${{ github.event.before }}
      head_sha: ${{ github.sha }}
    permissions:
      contents: read
      security-events: write

  dependency-scan:
    name: Dependency Scan
    uses: ./.github/workflows/_dependency-scan.yml
    with:
      changed_only: true
      base_sha: ${{ github.event.before }}
      head_sha: ${{ github.sha }}
    permissions:
      contents: read
      security-events: write
