name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-container-scan:
    name: Build and Container Scan
    uses: ./.github/workflows/build-and-container-scan.yml
    permissions:
      contents: read
      packages: write
      security-events: write
