name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-application:
    name: Build Application
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      push-image: true

  container-scan:
    name: Container Scan
    needs: build-application
    uses: ./.github/workflows/container-scan.yml
    permissions:
      contents: read
      packages: read
      security-events: write
      actions: read
      pull-requests: read
    with:
      image-ref: ${{ needs.build-application.outputs.image_ref }}
